# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
    - master
        
         


variables:
  - group: TripShop
  - name: configuration
    value: 'Release'
  - name: sdk
    value: 'iphoneos'

pool:
  vmImage: 'macOS-10.14'

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'Certificates.p12'
    keychain: 'temp'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'OTA_Prvision_profile.mobileprovision'


   


- task: FlutterInstall@0
  inputs:
    channel: 'stable'
    version: 'latest'

# - task: FlutterBuild@0
#   inputs:
#     target: 'all'
#     projectDirectory: '.'
#     entryPoint: 'lib/main_dev.dart'
- task: CocoaPods@0
  displayName: "Install CocoaPods dependencies"
  inputs:
    workingDirectory: 'ios'

- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: '$(configuration)'
    sdk: '$(sdk)'
    xcWorkspacePath: ios/Runner.xcworkspace/'
    scheme: 'Runner'
    xcodeVersion: 'specifyPath'
    xcodeDeveloperDir: '/Applications/Xcode_11.3.app/Contents/Developer'
    packageApp: true
    signingOption: 'manual'

    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'

- task: CopyFiles@2
  inputs:
    contents: '**/*.ipa'
    targetFolder: '$(build.artifactStagingDirectory)'
    overWrite: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(build.artifactStagingDirectory)/output/$(sdk)/$(configuration)' 
    artifactName: 'drop' 
    publishLocation: 'Container'
- task: AndroidSigning@3
  displayName: 'Signing and aligning APK file(s) **/*.apk'
  inputs: 
  
    apkFiles: '**/*.aab'
    apksign: true
    apksignerArguments: --min-sdk-version 23
    apksignerKeystoreFile: tripshop.jks
    apksignerKeystorePassword: $(KEYSTORE_PASSWORD)
    apksignerKeystoreAlias: $(KEY_ALIAS)
    apksignerKeyPassword: $(KEY_PASSWORD)
    zipalign: false
  


- task: CopyFiles@2
  inputs:
    contents: '**/*.aab'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'drop'



