name: ota
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+16

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.1.3
  http: ^0.12.0+4
  dio: ^3.0.9
  shared_preferences: ^0.5.6+3
  json_annotation: ^3.0.1
  device_info: ^0.4.2+4
  intl: ^0.16.1
  flutter_date_pickers: ^0.1.4
  flutter_rating_bar: ^3.0.1+1
  google_maps_flutter: ^0.5.28+1
  connectivity: ^0.4.3+2
  get_it: ^4.0.2
  flutter_typeahead: ^1.8.6
  flutter_spinkit: ^4.1.2
  firebase_crashlytics: ^0.1.4+1
  flutter_credit_card: ^0.1.3
  flutter_svg: ^0.18.0
  flare_flutter: ^2.0.6
  carousel_pro: ^1.0.0
  equatable: ^1.2.3
  pin_code_fields: ^5.0.1

  flutter_secure_storage: ^3.3.3
  intl_phone_number_input: ^0.5.1
  google_sign_in: ^4.5.4
  flutter_facebook_login: ^3.0.0

  shimmer: ^1.1.1
  path_provider: ^1.6.17

  package_info: ^0.4.3

  curl: ^1.0.0

  age: ^0.0.1


  crypto: ^2.1.5
  encrypt: ^4.0.3

  firebase_messaging: ^7.0.3

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^3.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lang/en.json
    - assets/lang/ar.json
    - assets/images/facebook_icon.png
    - assets/images/google_icon.png
    - assets/images/cruise.png
    - assets/images/event.png
    - assets/images/flights.png
    - assets/images/hotels.png
    - assets/images/package.png
    - assets/images/transfer.png
    - assets/images/plane.png
    - assets/images/location.png
    - assets/images/calender.png
    - assets/images/flight_list_image1.png
    - assets/images/flight_list_image2.png
    - assets/images/american_airlines.png
    - assets/images/path1.png
    - assets/images/path2.png
    - assets/images/morning.png
    - assets/images/afternoon.png
    - assets/images/evening.png
    - assets/images/night.png
    - assets/images/circular.png
    - assets/images/Economy.png
    - assets/images/Economy-Premium.png
    - assets/images/business.png
    - assets/images/First-class.png
    - assets/images/multiple-icon.png
    - assets/images/credit_card.png
    - assets/images/apple_pay.png
    - assets/images/check.png
    - assets/images/cab_icon.png
    - assets/images/minibus_car.png
    - assets/images/minivan_car.png
    - assets/images/standard_car.png
    - assets/images/maps.png
    - assets/images/activity1.png
    - assets/images/activity2.png
    - assets/images/activity3.png
    - assets/images/barcode.png
    - assets/images/logo.png
    - assets/loading.gif
    - assets/screenshot_icon.png
    - assets/clipboard.png
    - assets/nobookings.png

    - assets/images/default_profile_cover.png
    - assets/images/default_profile_pic.png
    - assets/images/dash_board_pic1.png
    - assets/images/dash_board_pic2.png
    - assets/images/dashboard/tripshop_logo.png
    - assets/images/dashboard/icon_flight.png
    - assets/images/dashboard/icon_hotel.png
    - assets/images/dashboard/icon_package.png
    - assets/images/dashboard/icon_activities.png
    - assets/images/dashboard/icon_transfer.png
    - assets/images/dashboard/icon_cruise.png
    - assets/images/temp/hotel_temp.png
    - assets/images/temp/package2.jpg
    - assets/images/dashboard/dashboard_bg.png
    - assets/images/dashboard/cover.jpg
    - assets/images/dashboard/logo_plane.png

    - assets/images/ameneties/wifi.png
    - assets/images/ameneties/pool.png
    - assets/images/ameneties/gym.png
    - assets/images/ameneties/ac.png
    - assets/images/ameneties/bar.png
    - assets/images/ameneties/restuarant.png
    - assets/images/ameneties/pets.png
    - assets/images/ameneties/garden.png
    - assets/images/ameneties/parking.png
    - assets/loader.flr
    - assets/images/user.svg
    - assets/images/female.svg
    - assets/images/profile_img.png
    - assets/images/logout.png
    - assets/images/no_image_available.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/roboto_bold.ttf
        - asset: assets/fonts/roboto_medium.ttf
        - asset: assets/fonts/roboto_regular.ttf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
